v = ver;
any(strcmp({v.Name}, 'WLAN Toolbox')) % Must return true (1)

Fs          = 500e3;
CaptureTime = 2;           % seconds
TotalSamples = round(Fs * CaptureTime);

rxObj = comm.SDRuReceiver( ...
    'Platform',          'B210', ...
    'SerialNum',         '34C78FD', ...
    'MasterClockRate',   30e6, ...
    'DecimationFactor',  60, ...
    'SamplesPerFrame',   TotalSamples, ...
    'CenterFrequency',   2.4e9, ...
    'ChannelMapping',    [1 2], ...    
    'Gain',              [70 70], ...
    'OutputDataType',    'double');

% Capture a batch of samples (e.g., 200,000 samples = 10 ms)
capturedData = [];
for k = 1:5
    [data, len, overflow] = rx();
    if ~overflow && len > 0
        capturedData = [capturedData; data]; %#ok<AGROW>
    end
end
release(rx);

